name: pr-test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # build matrix (all desired configurations)
    strategy:
      matrix:
        os: [ubuntu-24_04, macos-15]
        build-type: [Debug, Release]
        camp: [OFF, ON]

    # Steps for building and running tests.
    steps:

    - name: Checking out repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Installing dependencies
      run: |
        apt-get update && apt-get install -y --no-install-recommends \
          cmake \
          gcc \
          g++ \
          gfortran \
          git \
          make \
          ninja-build \
          pkg-config

    - name: Configuring aerosol models (${{ matrix.build-type }})
      run: |
        cmake -S . -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
        -DENABLE_CAMP=${{ matrix.camp}}

    - name: Building aerosol models (${{ matrix.build-type }})
      run: ninja
